---
- name: Install nginx
  become: yes
  apt: name=nginx state=latest

- name: Check whether the default Nginx site config exists
  stat:
    path: /etc/nginx/sites-enabled/default
  register: default_nginx_site

- name: Disable NGINX Default Virtual Host
  become: yes
  command:
    cmd: unlink /etc/nginx/sites-enabled/default
  when: default_nginx_site.stat.exists

- name: copy the nginx config file and restart nginx
  become: yes
  template:
    src: terraform.cfg
    dest: /etc/nginx/sites-available/terraform.cfg

- name: create symlink
  become: yes
  file:
    src: /etc/nginx/sites-available/terraform.cfg
    dest: /etc/nginx/sites-enabled/terraform
    state: link

- name: restart_nginx
  become: yes
  service: name=nginx state=restarted enabled=yes
